# Python program to check string generated by regualr expression

#import re module re module provides support for regular expressions
import re

# regular expression a*b*
re1 = '^[a][b]*'
	
# function to check string for re1
def check1(s):

	# pass the re1 & sin search() method
	if(re.search(re1, s)):
		print("Valid String")
		
	else:
		print("Invalid String")
	
# regular expression (ab)*(aa + bb) => (ab)*aa +(ab)*bb
re2 = '^[ab]*bb$' 
re3 = '^[ab]*aa$'
	
# function to check string for re1
def check2(s):

	# pass the re1 & sin search() method
	if(re.search(re2, s) or re.search(re3, s)):
		print("Valid String")
		
	else:
		print("Invalid String")

# Driver Code to run above function
if __name__ == '__main__' :
	
	# Enter the string & function call check1
	string1 = "aaabbbbbb"
	check1(string1)

	string2 = "aaaaaa"
	check1(string2)

	string3 = "bbbbbaaaaa"
	check1(string3)
	
	# Enter the string & function call check2
	string1 = "abababbb"
	check2(string1)

	string2 = "bbbbbbababab"
	check2(string2)

